# Generated by Django 4.2 on 2023-04-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_receita_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(blank=True, decimal_places=2, help_text='R$', max_digits=10, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=2, help_text='R$', max_digits=10, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('Investimento', 'Investimento'), ('Presente', 'Presente'), ('Prêmio', 'Prêmio'), ('Salário', 'Salário'), ('Outros', 'Outros')], max_length=12, null=True)),
            ],
        ),
    ]
