# Generated by Django 4.2 on 2023-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.CharField(max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(max_length=12)),
                ('comprovante', models.FileField(upload_to='')),
            ],
        ),
    ]
