# Generated by Django 4.2 on 2023-04-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
